AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  FunctionName:
    Type: String
    Default: attendance-alert-function-dev

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.12
    Environment:
      Variables:
        ENV: !Ref Environment

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: ./src/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        # Add other IAM policies as needed
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !Sub arn:aws:s3:::${Environment}-*/*

  MyFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MyFunction}
      RetentionInDays: 14

Outputs:
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt MyFunction.Arn
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref MyFunction
